In [2]:
import numpy as np

In [3]:
np.__version__

'2.3.4'

## Create and Read

### 1D Array

In [4]:
arr1 = np.array([1,2,3,4,5])

In [5]:
arr1

array([1, 2, 3, 4, 5])

#### 2D array

In [7]:
arr2 = np.array([[1,2,3],[4,5,6]])

In [8]:
arr2

array([[1, 2, 3],
       [4, 5, 6]])

In [9]:
arr2.shape

(2, 3)

In [10]:
arr2.size

6

In [11]:
arr2.ndim

2

#### 3D array

In [13]:
arr3 = np.array([[[1,2,3],[4,5,6]], [[1,2,3],[4,5,6]], [[1,2,3],[4,5,6]]])

In [14]:
arr3

array([[[1, 2, 3],
        [4, 5, 6]],

       [[1, 2, 3],
        [4, 5, 6]],

       [[1, 2, 3],
        [4, 5, 6]]])

In [15]:
arr3.ndim

3

In [16]:
arr3.size

18

In [17]:
arr3.shape

(3, 2, 3)

## create Random Arrays

In [18]:
randArr = np.random.rand(3,2,3)
randArr

array([[[0.14254646, 0.02951079, 0.78577206],
        [0.55764294, 0.7502802 , 0.42831835]],

       [[0.73681746, 0.91288727, 0.58696428],
        [0.46841565, 0.59070128, 0.94494472]],

       [[0.55649624, 0.54271926, 0.8732935 ],
        [0.67684692, 0.5603193 , 0.19134952]]])

In [19]:
randArr.dtype

dtype('float64')

In [20]:
zeros = np.zeros((3,2,3))
zeros

array([[[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]]])

In [21]:
full = np.full((3,2,3),9)
full

array([[[9, 9, 9],
        [9, 9, 9]],

       [[9, 9, 9],
        [9, 9, 9]],

       [[9, 9, 9],
        [9, 9, 9]]])

In [22]:
arr3[0]

array([[1, 2, 3],
       [4, 5, 6]])

In [23]:
arr3[0][0]

array([1, 2, 3])

In [24]:
arr3[0][0][1]

np.int64(2)

In [25]:
arr3[0:2]

array([[[1, 2, 3],
        [4, 5, 6]],

       [[1, 2, 3],
        [4, 5, 6]]])

In [26]:
arr3[-1]

array([[1, 2, 3],
       [4, 5, 6]])

In [27]:
arr3[1][1][1]

np.int64(5)

In [28]:
arr3[1,1,1]

np.int64(5)

## Update and Delete the Numpy array